---

- name: Add nodes
  community.docker.docker_swarm:
    state: join
    join_token: "{{ lookup('ansible.builtin.file', '/tmp/manager') }}"
    remote_addrs: [ "{{ hostvars[groups.control_main[0]]['ansible_default_ipv4']['address']:2377 }}" ]

- name: Create etcd cert dir.
  ansible.builtin.file:
    path: "/etc/ssl/etcd/"
    state: directory

- name: Upload etcd certs.
  ansible.builtin.copy:
    src: "/tmp/{{item}}"
    dest: "/etc/ssl/etcd/{{item}}"
    mode: '0644'
  with_items:
    - "ca_etcd.pem"
    - "{{ inventory_hostname }}.crt"
    - "{{ inventory_hostname }}.csr"
    - "{{ inventory_hostname }}-key.pem"
    - "{{ inventory_hostname }}-peer.crt"
    - "{{ inventory_hostname }}-peer.csr"
    - "{{ inventory_hostname }}-peer-key.pem"
    - "{{ inventory_hostname }}-peer.pem"
    - "{{ inventory_hostname }}.pem"

- name: Create balancer cert dir.
  ansible.builtin.file:
    path: "/etc/ssl/balancer/"
    state: directory

- name: Upload balancer certs.
  ansible.builtin.copy:
    src: "/tmp/{{item}}"
    dest: "/etc/ssl/balancer/{{item}}"
    force: true
    mode: '0644'
  with_items:
    - "ca_etcd.pem"
    - "balancer.crt"
    - "balancer.csr"
    - "balancer-key.pem"
    - "client.crt"
    - "client.csr"
    - "client.pem"
    - "client-key.pem"
    - "balancer.pem"

- name: Create balancer config dir.
  ansible.builtin.file:
    path: "/etc/balancer"
    state: directory

- name: Upload balancer config.
  ansible.builtin.copy:
    src: "/source/config/load-balancer.conf"
    dest: "/etc/balancer/load-balancer.conf"
    mode: '0644'

- name: Create local database dir.
  ansible.builtin.file:
    path: "/db/etcd/{{ inventory_hostname }}-etcd"
    state: directory