---

- name: Копирование compose.yaml
  ansible.builtin.copy:
    src: "/source/config/compose.yaml"
    dest: "/tmp/compose.yaml"


- name: Получение ссылки на публичный discovery сервер etcd
  ansible.builtin.uri:
    url: "https://discovery.etcd.io/new?size={{ groups.control_all|length }}"
    return_content: true
  register: discovery


- name: Deploy stack from base compose file and override the web service
  community.docker.docker_stack:
    state: present
    name: servers
    compose:
      - "/tmp/compose.yaml"
      - services:
          etcd:
            environment:
              ETCD_DISCOVERY: "{{ discovery.content }}"







#
#- name: Деплой swarm
#  ansible.builtin.shell: "{{ item }}"
#  with_items:
#    - "sed -i \"s|discovery_url|{{ discovery.stdout }}|g\" /mnt/swarm/repo/compose.yml"
#    - "cat /mnt/swarm/repo/compose.yml"
#    - "docker stack deploy --detach=false -c /mnt/swarm/repo/compose.yml servers"
#  args:
#    executable: /bin/bash
#  register: swarm_dump
