---
#- name: ---
#  ansible.builtin.include_tasks: /ansible_root/playbooks/tasks/_0_utility/cert/_0_create.yaml
#  vars:
#    ca: { "path":"/etc/ssl/etcd/","name":"ca_etcd" }
#    list: [
#      { "path":"/etc/ssl/etcd/","name":"{{loop_hostname}}",
#             "key_usage":[digitalSignature],"extended_key_usage":[serverAuth,clientAuth],
#             "subject_alt_name":'IP:127.0.0.1,IP:192.168.2.2,IP:192.168.2.10,{{ groups.control_all | map("regex_replace", "^(.*)$", "DNS:\1-etcd") | join(",") }},DNS:balancer'},
#      { "path": "/etc/ssl/etcd/","name": "{{loop_hostname}}-peer",
#        "key_usage": [ digitalSignature ],"extended_key_usage": [ serverAuth,clientAuth ],
#        "subject_alt_name": 'IP:127.0.0.1,IP:192.168.2.2,IP:192.168.2.10,{{ groups.control_all | map("regex_replace", "^(.*)$", "DNS:\1-etcd") | join(",") }},DNS:balancer' },
#      {"path":"/etc/ssl/etcd/","name":"client",
#       "key_usage":[ keyEncipherment,dataEncipherment ],"extended_key_usage":[clientAuth],
#       "subject_alt_name":''},
#      { "path": "/etc/ssl/balancer/","name": "balancer",
#        "key_usage": [ digitalSignature ],"extended_key_usage": [ serverAuth,clientAuth ],
#        "subject_alt_name": 'IP:127.0.0.1,IP:192.168.2.2,{{ groups.control_all | map("regex_replace", "^(.*)$", "DNS:\1-etcd") | join(",") }},DNS:balancer' }]
#    renew: false
#  loop: "{{ groups.control_all }}"
#  loop_control:
#    label: "{{ loop_hostname }}"
#    loop_var: loop_hostname

- name: Копирование сертификатов
  ansible.builtin.copy:
    src: "/etc/ssl/etcd/{{item}}"
    dest: "/etc/ssl/balancer/{{item}}"
    force: true
    remote_src: yes
  with_items:
    - "ca_etcd.pem"
    - "client.crt"
    - "client.csr"
    - "client.pem"
    - "client-key.pem"

- name:  find balancer certs
  ansible.builtin.find:
    paths: /etc/ssl/balancer/
  register: certs

- name: Копирование certs в ansible
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: /tmp/
    flat: yes
  with_items: "{{certs.files}}"

- name:  find etcd certs
  ansible.builtin.find:
    paths: /etc/ssl/etcd/
  register: certs

- name: Копирование certs в ansible
  ansible.builtin.fetch:
    src: "{{ item.path }}"
    dest: /tmp/
    flat: yes
  with_items: "{{certs.files}}"


- name: Загрузка утилиты etcdctl
  ansible.builtin.get_url:
    url: "https://github.com/etcd-io/etcd/releases/download/v3.5.16/etcd-v3.5.16-linux-amd64.tar.gz"
    dest: "/tmp"
  register: discovery

- name: Unarchive etcdctl
  ansible.builtin.unarchive:
    src: /tmp/etcd-v3.5.16-linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy manager worker
  ansible.builtin.copy:
    src: "/tmp/etcd-v3.5.16-linux-amd64/{{item}}"
    dest: "/usr/bin/{{item}}"
    remote_src: yes
  loop:
    - etcd
    - etcdctl
    - etcdutl