


- hosts: control_all
  become: true
  tasks:
    - name: Delete swarm.
      ansible.builtin.include_tasks: /source/playbooks/_1_swarm/_0_delete.yaml

- hosts: control_main
  name: Init swarm.
  become: true
  tasks:
#    - name: test.
#      ansible.builtin.include_tasks: ./_1_swarm/test.yaml
    - name: Create master, join-tokens.
      ansible.builtin.include_tasks: /source/playbooks/_1_swarm/_1_init.yaml

- hosts: control
  become: true
  tasks:
    - name: Установка swarm.
      ansible.builtin.include_tasks: /source/playbooks/_1_swarm/_2_join.yaml

- hosts: control_main
  name: deploy
  become: true
  tasks:
    - name: Deploy stack.
      ansible.builtin.include_tasks: /source/playbooks/_1_swarm/_3_deploy.yaml
